### ISSUE TITLE
Can not change Contant-Type when data is FormData

### ISSUE THREAD

**Issue by TabrisK** [axios/axios#1603]
```javascript
axios({
                method: "PUT",
                url: url,
                transformRequest: [function (data, headers) {
                    // Do whatever you want to transform the data
                    return formData;
                }],
                headers: {
                    'Content-Type': file.type
                },
                "withCredentials": false
            });
```

Launched request with Content-Type：
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryPz13ZA77aLqgPlwB

**Comment by Oceanswave** [comment]
Looks like when axios detects form data in the request body, it auto-sets a multipart/form-data header, overriding the header value.

This gets tricky if you're mocking responses from the server with something like Nock, which will see a different boundary value in the response -or- needing to interact with a api that expects a multipart/related content type.

**Comment by ppozniak** [comment]
I am just facing the same issue.
Have you found any way to solve this @TabrisK

**Comment by TabrisK** [comment]
@ppozniak 
Unfortunately, I can't change the behavior of axios. Finally I solve the problem by using **XMLHttpRequest**.

**Comment by ppozniak** [comment]
https://github.com/axios/axios/blob/283d7b306ce231f092d28e01713905e5c1600d14/lib/adapters/xhr.js#L16
This is probably the cause.

**Comment by ppozniak** [comment]
One really ugly hack, without rewriting the app would be to hack object's prototype. This will make `Content-type` stay as it is.
```
transformRequest: payload => {
       // ...
        Object.setPrototypeOf(formData, null);
        return formData;
      },
```

**Comment by jasonsaayman** [comment]
Fixed with #1773

**Comment by chinesedfan** [comment]
@jasonsaayman I am afraid #1773 didn't solve it. Reopen for confirming.

**Comment by tymmesyde** [comment]
Is there any workaround?

**Comment by Masaokb** [comment]
Has this issue been solved?

In my case, using `axios.request`, `content-type` header disappeared even when I specified, but using `axios.post` didn't seem to have any problem.

**Comment by manamika** [comment]
In my case, i need to override the content-type to have a version - Content-Type: multipart/form-data;version=2.0.0;boundary=B_someBoundary. Is this something that will be allowed?

**Comment by Kalinin** [comment]
I have the same bug as described in issue. Still happens.

**Comment by YsBunkerchain** [comment]
The Get method also not able to change the content-type when I put the data as FormData.

**Comment by shivanshr** [comment]
I am not able to do so with POST(mulitpart/form-data) request, I can not set header['Content-Type'] 'mulitpart/form-data', it always changes to 'text/plain;charset=UTF-8'.
"axios": "^0.21.1",
"react-native": "0.63.4"

**Comment by norbertsongin** [comment]
It's because of this part https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L18-L20
Looks like it was first reported in 2017 https://github.com/axios/axios/issues/767 but was closed without being fixed

Removing this part worked for me

**Comment by JonathanSchndr** [comment]
:( same issue here in nuxt-auth with axios as dep.

**Comment by jasonsaayman** [comment]
closing due to being very stale, if this is still relevant please open a new issue
