### ISSUE TITLE
0.21.2: Response interceptor not called when request interceptor is attached

### ISSUE THREAD

**Issue by nerdbeere** [axios/axios#4012]
#### Describe the bug
With the latest release `0.21.2` the response interceptor is no longer called when a request interceptor is attached.

#### To Reproduce

Not working: https://jsfiddle.net/yedqwjma/
```js
// response interceptor won't be executed
axios.interceptors.response.use((config) => {
	console.log('response interceptor');
  return config;
});

axios.interceptors.request.use((config) => {
	console.log('request interceptor');
  return config;
});

axios.get('https://jsonplaceholder.typicode.com/todos/1');
```

Working Case with 0.21.1: https://jsfiddle.net/n05rdb49/

#### Expected behavior
Response interceptor should be executed

#### Environment
 - Axios Version 0.21.2

#### Additional context/Screenshots
Not required

**Comment by nerdbeere** [comment]
@jasonsaayman found the issue and added a test, maybe you could have a look: https://github.com/axios/axios/pull/4013

**Comment by exneval** [comment]
faced the same issue

**Comment by jadeydi** [comment]
faced the same issue

**Comment by oneness0** [comment]
+1

**Comment by maheshdama13** [comment]
+1

**Comment by z0y1** [comment]
+1

**Comment by vesper8** [comment]
+1 This regression just cost me my entire afternoon =/

**Comment by bryce0516** [comment]
same here

**Comment by lvjiaxuan** [comment]
oh my god,

**Comment by jasonsaayman** [comment]
Waiting for the build to pass and then I will release this, thanks @nerdbeere for the fix

**Comment by jasonsaayman** [comment]
I have released and tagged a new version. Sorry for the frustration caused, I will work on a plan tomorrow to make release break less and bring some consistency to the release schedule etc.

**Comment by ddolcimascolo** [comment]
Hi guys,

Can someone confirm that v0.21.3 fixes the issue? I'm asking because our builds are still failing when upgrading from 0.21.1 to 0.21.3 (and the errors we get are the same as the one we had when trying an upgrade to 0.21.2).

To be honest, I didn't inspect the failures in details yet, but retrying the build reproduces the error, so either:
 - We're hit by this interceptors issue (we do use interceptors) and it's not fixed
 - There's another regression and I can give you more details tomorrow, or Monday morning

Luckily we have tests that caught the regressions in time 😅 

Thx,
David

**Comment by bryce0516** [comment]
axios 0.21.3 is properly working!

**Comment by ddolcimascolo** [comment]
Thx for confirming. I've analyzed my build failures and created https://github.com/axios/axios/issues/4016

**Comment by gfortaine** [comment]
@ddolcimascolo It should be fixed with 0.21.4 https://github.com/axios/axios/pull/4020

**Comment by Shajansheriff** [comment]
@nerdbeere Thanks for saving our day!

**Comment by zohairkazmi** [comment]
it works with 0.21.4 but fails with 0.24.0. Somebody has put the buggy code back :)

**Comment by zohairkazmi** [comment]
it works with 0.23.0 as well but not 0.24.0

**Comment by Note45** [comment]
I have the same issue with Axios version 0.21.2. To fix I updated to version 0.23.0
