### ISSUE TITLE
Typescript types do not make sense

### ISSUE THREAD

**Issue by euberdeveloper** [axios/axios#4176]
#### Describe the bug
I updated from axios `0.21.1` to `0.22.0` but typescript started giving me strange errors

I then noticed that the types declarations changed and they do not make much sense. 

I can see that the `post` signature is:
```
post<T = never, R = AxiosResponse<T>>(url: string, data?: T | undefined, config?: AxiosRequestConfig<T> | undefined): Promise<R>
```

I don't really get why the response data object should be, by default, equal to the object passed as body, there is really no sense for that as a default behaviour. It should be AxiosResponse<any> instead.

For the `axios` function, the returned object is even a `never`, in `axios(config: AxiosRequestConfig<any>): AxiosPromise<never>`.

Of course I can just put the types specifications, but it makes the code longer and ugly when there would be many times no reason for that.

#### To Reproduce
To reproduce it, just try to make a post request

```js
const response = await axios.post(
                CONFIG.API_UNITN.CLESIUS.SECURITY.AUTH_SERVICE_URL,
                data.toString()
            ); // the response has AxiosResponse<string> type
```

#### Expected behavior
There should not be types assumptions such as the one made

#### Environment
 - Axios Version 0.22.0
 - Adapter http
 - Browser any
 - Browser Version any
 - Node.js Version any
 - OS: Linux Ubuntu 20
 - Additional Library Versions none

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by BruceJi7** [comment]
You certainly can solve this issue by adding  `any`
Like so:
```ts
const { data }: any = await instance.get("/users/me");
```

**Comment by doitandbedone** [comment]
This has been fixed in [v.0.23.0](https://github.com/axios/axios/releases/tag/v0.23.0) by https://github.com/axios/axios/pull/4116. Can be closed as duplicate.

**Comment by icyJoseph** [comment]
I think we can close this issue. I had the exact same problem, and after upgrading to 0.23.0 it went away.

**Comment by Gabb-c** [comment]
So, maybe I faced a similar problem:

```ts
public async getContestTypeByName(name: string): Promise<ContestType> {
    return new Promise<ContestType>((resolve, reject) => {
      this.api
        .get(`${Endpoints.ContestType}/${name}`)
        .then((response: AxiosResponse<ContestType>) => resolve(response.data)) // ts error in this line
        .catch((error: AxiosError<string>) => reject(error));
    });
  }
```
TypeScript Error log:
```log
Argument of type '(response: AxiosResponse<ContestType>) => void' is not assignable to parameter of type '(value: AxiosResponse<unknown, any>) => void | PromiseLike<void>'.
  Types of parameters 'response' and 'value' are incompatible.
    Type 'AxiosResponse<unknown, any>' is not assignable to type 'AxiosResponse<ContestType, any>'.
      Type 'unknown' is not assignable to type 'ContestType'.ts(2345)
```
Fixed by typing the **axios.get** method itself:
```ts
public async getContestTypeByName(name: string): Promise<ContestType> {
    return new Promise<ContestType>((resolve, reject) => {
      this.api
        .get<ContestType>(`${Endpoints.ContestType}/${name}`)  //  <- here
        .then((response) => resolve(response.data))
        .catch((error: AxiosError<string>) => reject(error));
    });
  }
```
Don't if it's the right way, but works fine.
[Reference](https://github.com/Gabb-c/pokenode-ts/blob/master/src/clients/contest.client.ts)

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest pre-release version and open a new issue should this error still be relevant?

Thanks
