### ISSUE TITLE
AxiosRequestHeaders type breaks from 0.21.4 to 0.22.0

### ISSUE THREAD

**Issue by mxsxs2** [axios/axios#4193]
#### Describe the bug
The type has changed and now I am getting linting errors on a working code.
I get _Element implicitly has an 'any' type because index expression is not of type 'number'.ts(7015)_ error when I try to access the headers by their name on a `AxiosRequestHeaders` object.

For example accessing a common header in `transfomRequest` where the content of headers is:
![image](https://user-images.githubusercontent.com/13612429/137500608-0c174932-6a44-454e-9a34-2afe17e9ddd2.png)

If I try to access the common _Accept_ header key, then I will get the above error. 

I think the issue is at: https://github.com/axios/axios/blob/1025d1231a7747503188459dd5a6d1effdcea928/index.d.ts#L3

The type should be:
```typescript
export type AxiosRequestHeaders = Record<string, Record<string, string>>; 
```

Possibly the `AxiosResponseHeaders` has the same issue. 

#### To Reproduce
```typescript 
import axios from 'axios'

axios({
    method: 'post',
    url: '/user/12345',
    data: {
        firstName: 'Fred',
        lastName: 'Flintstone',
    },
    transformRequest: (_, headers) => {
        if(headers)
            delete headers.common['Accept'] //Error occurs here
    },
})
    .then(function (response) {
        console.log(response)
    })
    .catch(function (error) {
        console.log(error)
    })
```

#### Expected behavior
Expected to not raise an error there

#### Environment
 - Axios 0.23.0
 - TypeScript 4.4.4

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/13612429/137501665-a9193bb5-92a7-4da5-bce2-1ef69165fb7f.png)

**Comment by RaddishIoW** [comment]
I have this issue when trying to set the default headers thus:
```typescript
if (axios.defaults.headers != null) {
  axios.defaults.headers.common['X-CSRFToken'] = csrftoken
}
```
so setting the `AxiosRequestTransformer` to use `HeadersDefaults` wouldn't fix that?

**Comment by RaddishIoW** [comment]
It doesn't though. I get the error. This issue isn't specific to transform response or transform request as far as I can see.

**Comment by Sirusblk** [comment]
I think that's a separate issue because `axios.defaults.headers.common` doesn't reference `AxiosRequestTransformer`.

Side stepping that, when I run this code:
```typescript
import axios from 'axios';

const csrftoken: string | undefined = "foo";

if (axios.defaults.headers != null) {
  axios.defaults.headers.common['X-CSRFToken'] = csrftoken
}

console.log(typeof csrftoken === typeof axios.defaults.headers.common['X-CSRFToken']);
```

I get the output `true`.

**Comment by mxsxs2** [comment]
> I could be wrong but I think a better fit would be to change the `AxiosRequestTransformer` to use `HeadersDefaults` instead. That specifically has properties such as common, delete, get, and more. It has the added benefit of not breaking any existing use cases in the typescript tests.

I think you are right. `HeadersDefaults` would be a better fit for the _headers_ parameter's type in `AxiosRequestTransformer`.

Your code at https://github.com/axios/axios/issues/4193#issuecomment-945204765 works. It should would work with the transformers too then. It is also stricter, which is always good.

**Comment by Sirusblk** [comment]
I think we need the maintainers are going to have to weigh in on this. The current behavior is to just use headers without setting values for common, or delete only, etc. HeaderDefaults where you can set default headers for delete only, common amongst all, etc. currently only apply when constructing your axios object.

**Comment by rustlestuff** [comment]
Tried to update my outdated 0.21.1 to 0.24.0
Got an `Object is possibly 'undefined'.  TS2532`
```
    14 |     myInstance.interceptors.request.use(config => {
  > 15 |         config.headers.get['X-Language'] = i18n.language;
       |         ^
    16 |         return config;
    17 |     })
```
Trying to do something similar to @ghost91- I believe:
Updating the X-Language header when a user changes their language, but if I don't define this in the interceptor as follows, it won't respond to changes.

**Comment by serebrov** [comment]
Note that there is also this [example in the README](https://github.com/axios/axios#axioscreateconfig):

```
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});
```

In this case the custom header will be at the root of the `headers` object:

```
console.log(instance.defaults.headers)

{
  "X-Custom-Header": "foobar",
  common: { Accept: "application/json, text/plain, */*" },
  delete: {  },
  get: {  },
  head: {  },
  patch: { "Content-Type": "application/x-www-form-urlencoded" },
  post: { "Content-Type": "application/x-www-form-urlencoded" },
  put: { "Content-Type": "application/x-www-form-urlencoded" },
}
```

I am not sure if this is the documentation issue and it should be `headers: { common: 'X-Custom-Header': 'foobar'} }` or a type issue and `HeaderDefaults` should also allow arbitrary keys in the root.

**Comment by alexcoliveira1** [comment]
Adding more info on what others have tried:
I tried to follow the official docs here https://axios-http.com/docs/config_defaults

I made this code
```
axios.defaults.headers.common.Accept = '';
```
Typescript complained about `Object is possibly 'undefined'.  TS2532` referring to `headers`, ok. Let's wrap it in an if statement.

```
if (axios.defaults.headers) {
  axios.defaults.headers.common.Accept = '';
}
```
Now I get `Property 'Accept' does not exist on type 'string'.  TS2339`

And that's because `headers` if of type `Record<string, string>`
```
export interface AxiosRequestConfig<T = any> {
  ...
  headers?: Record<string, string>;
  ...
}
```

I hope it's fixed soon.

**Comment by Jesus-Escalona** [comment]
+ 1 

Currently dealing with `object is not assignable to type 'string'.` When trying to instantiate as

```
axios.create({
                headers: {
                    common: headerData,
                },
            })
```

**Comment by ghost91-** [comment]
@Jesus-Escalona your last example works correctly at runtime, it’s only a typing issue. The types need to be fixed accordingly.

**Comment by meditaknorr** [comment]
I have been looking arround for a way to update headers root props,
I have used .common but it doesn't update the prop Secure-Code.
Is there a way?

**Comment by meditaknorr** [comment]
Hi there,
I would like to know how I can update the props that are on my headers root.
I tried with **axios.defaults.he
![axios bug](https://user-images.githubusercontent.com/51007331/144625535-324484b0-9db1-40ca-970c-4d9f11b1f556.png)
ader.common[x] = ÿ** and it is going to header: { ..., common:  { ....here } },
I want to edit the props on root.

Please Help. I'm using this new axios version with typescript.
[Friendly Suggestion for future]: axios.defaults.headers.root[x] = z.
root to access root field.

**Comment by halimb** [comment]
Still having this issue with version `0.25.0`

**Comment by steve-ross** [comment]
I believe the main issue is related to this Omit: ```
export interface AxiosDefaults<D = any, T = any> extends Omit<AxiosRequestConfig<D>, 'headers'> {
  headers: HeadersDefaults | T;
}
```

**Comment by towry** [comment]
Stil having this issue with version `0.26.0`

```
Element implicitly has an 'any' type because expression of type '"X-XSRFToken"' can't be used to index type 'string | number | boolean'.
  Property 'X-XSRFToken' does not exist on type 'string | number | boolean'.ts(7053)
```

```
Element implicitly has an 'any' type because expression of type '"Content-Type"' can't be used to index type 'string | number | boolean'.
  Property 'Content-Type' does not exist on type 'string | number | boolean'.ts(7053)
```

**Comment by gpa** [comment]
Another problem is that when accessing values via `.defaults.headers.common` every single values is set and of type `string, string | number | boolean` ! but the value can be undefined.

**Comment by luizfelipelaviola** [comment]
Axios has changed the `defaults` object. Now we can specify defaults per method.
To assign to every HTTP method, just use:

```ts
axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
```

Example now:
```ts
axios.defaults.baseURL = 'https://api.example.com';
axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';`
```

Documentation: https://axios-http.com/docs/config_defaults

**Comment by steve-ross** [comment]
Still doesn't fix the issue. Issue isn't _**assigning**_ defaults.  

The issue is you cannot define expected response headers (say from an API endpoint with documented header responses that are HeadersDefaults + more stuff)

This line is the issue: https://github.com/axios/axios/blob/ee151a7356ec4498af045dd830312822637890c9/index.d.ts#L115

Fix:
```typescript
export interface HeadersDefaults<T = any> {
  common: T | AxiosRequestHeaders;
  delete: AxiosRequestHeaders;
  get: AxiosRequestHeaders;
  head: AxiosRequestHeaders;
  post: AxiosRequestHeaders;
  put: AxiosRequestHeaders;
  patch: AxiosRequestHeaders;
  options?: AxiosRequestHeaders;
  purge?: AxiosRequestHeaders;
  link?: AxiosRequestHeaders;
  unlink?: AxiosRequestHeaders;
}
```

Then in my implementation:

```typescript

interface MyRequiredHeaders {
  authorization: AxiosRequestHeaders;
  cookie: AxiosRequestHeaders;
  'og-hmac': AxiosRequestHeaders;
  'x-csrftoken': AxiosRequestHeaders;
}

type MyRequiredHeaderDefaults = HeadersDefaults< MyRequiredHeaders >;

  /*

    Now the following works as expected

  */

  const headers: RC3HeadersDefaults = rc3.defaults.headers;
  headers.common.authorization = `Bearer ${token}`;
  headers.common.cookie = authCookie;
  headers.common['og-hmac'] = hmac;
  if (cookieData.csrftoken)
    headers.common['x-csrftoken'] = cookieData.csrftoken;

```
![image](https://user-images.githubusercontent.com/297351/163040326-00a111ae-8bc3-419c-bcd2-c2a85650c935.png)

**Comment by sk22** [comment]
i think this was fixed with this commit, right? https://github.com/axios/axios/commit/9f6ba5ee4326d33d2b84aef591582a26cc892d4d

**Comment by mxsxs2** [comment]
> i think this was fixed with this commit, right? [9f6ba5e](https://github.com/axios/axios/commit/9f6ba5ee4326d33d2b84aef591582a26cc892d4d)

That fixes this:
> I have this issue when trying to set the default headers thus:
> 
> ```ts
> if (axios.defaults.headers != null) {
>   axios.defaults.headers.common['X-CSRFToken'] = csrftoken
> }
> ```
> 
> so setting the `AxiosRequestTransformer` to use `HeadersDefaults` wouldn't fix that?


However, the issue with the transformer in my original report is still present.

https://github.com/axios/axios/commit/e6f9026d51d5e1386bc6935e563d95c375c45d02 looks like it will fix it. Ill check it once the new version is released.

**Comment by miralaur** [comment]
hi, still having the issue in "0.27.2",is someone made progress?

**Comment by jasonsaayman** [comment]
This should be fixed with the next release, a pre-release should be up a bit later today

**Comment by youngjaeji** [comment]
How can I get the pre-release?

**Comment by ozanhonamlioglu** [comment]
Hey there, any one tries to add `headers` on interceptors will probably have type errors. This because of `headers` property was any previously at verson 0.21.1 but after 0.21.4 to till 0.22.7 they have added type to headers and it brakes typescript user's heart.

An image from 0.21.1
<img width="500" alt="Screen Shot 2022-06-16 at 23 50 02" src="https://user-images.githubusercontent.com/47304816/174164716-4e1935b2-adae-4d60-a77e-68263a39b3a9.png">

Here is a simple solution

```typescript

interface MyAxiosRequestConfig extends Omit<AxiosRequestConfig, "headers"> {
	headers?: any; // this was "any" at v0.21.1 but now broken between 0.21.4 >= 0.27.2
}

export const onRequest = async (req: MyAxiosRequestConfig): Promise<MyAxiosRequestConfig> => {
   // do any additional header adds
   req.headers.common["Authorization"] = `Bearer ${token}`;
}

```
