### ISSUE TITLE
Imports error with CommonJS + Typescript

### ISSUE THREAD

**Issue by ivanpepelko** [axios/axios#5008]
#### Describe the bug
When using commonjs + typescript (in nest.js project, also reproduced standalone), imports are not consistent:
- default import: tsc passes, fails at runtime when trying to access `axios.default`
- star import: typescript check does not pass, produces working javascript
- require: workaround for imports

#### To Reproduce
See https://github.com/ivanpepelko/axios-import-require-issue
Attached:
- typescript sources (import-default.ts, import-star.ts, require.ts)
- resulting javascript files
- tsconfig
- package.json

#### Expected behavior
`axios.default` to be exported as per documentation.

#### Environment
 - Axios Version 1.0.0
 - Adapter: default for node16
 - Node.js Version 16
 - OS: Linux 5.19.12-arch1-1 x86_64 
 - Additional Library Versions: within nest.js framework and standalone as in attached repo

**Comment by bartschriever** [comment]
I am experiencing the exact same problem.

**Comment by arthurfiorette** [comment]
Probably related to #5000.

**Comment by VladimirMikulic** [comment]
Same issue as well.

**Comment by jasonsaayman** [comment]
See #5030 merged should fix this.

**Comment by SharjeelSafdar** [comment]
I'm also facing the same problem.

**Comment by BrettHoutz** [comment]
I still have this issue with axios v1.1.3.

TS import:
```ts
import axios from 'axios';
```

JS code transpiled by tsc:

```js
const axios_1 = require('axios');
// ...
const { data } = await axios_1.default.get('http://example.com');
```

This throws the exception:

```
TypeError: Cannot read properties of undefined (reading 'get')
```

**Comment by SharjeelSafdar** [comment]
I solved this problem with this workaround:

```ts
import { AxiosStatic } from "axios";
const Axios = require("axios") as AxiosStatic;
```
