### ISSUE TITLE
Axios calling request setHeader with function as value

### ISSUE THREAD

**Issue by KrayzeeKev** [axios/axios#5055]
#### Describe the bug
Axios is calling request.setHeader with a function as the value and this is causing nock to throw an error. I see nothing in the NodeJS documentation saying that a function is a valid value for a header (I was guessing perhaps you could provide a function it would call but there is nothing in the docs to suggest that). As such, I'm starting with this as an Axios bug and not a deficiency in nock's implementation of Request. 

It seems this is triggered by using axios-retry.

If, however, passing a function to request.setHeader is a valid thing, I'll close this and raise something on nock.

The function being passed to request.setHeader is the "get" method in the AxiosHeaders prototype.
```js
function(header, parser) {
    header = normalizeHeader(header);
    if (!header) return undefined;
    const key = findKey(this, header);
    if (key) {
      const value = this[key];
      if (!parser) {
        return value;
      }
      if (parser === true) {
        return parseTokens(value);
      }
      if (utils.isFunction(parser)) {
        return parser.call(this, value, key);
      }
      if (utils.isRegExp(parser)) {
        return parser.exec(value);
      }
      throw new TypeError('parser must be boolean|regexp|function');
    }
  }
```

The error returned by nock's request.setHeader is: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["0"]

#### To Reproduce

```js
'use strict';

const nock = require('nock');
const axios = require('axios');
const axiosRetry = require('axios-retry');

nock('http://localhost')
  .get('/')
    .times(2)
    .query(true)
    .delay(10000)
    .reply(200, [])
  .get('/')
    .reply(200, []);


const ax = axios.create();
let retryCount = 0;
axiosRetry(ax, {
  retries: 3,
  shouldResetTimeout: true,
  retryCondition: err => {
    if (err.code === 'ECONNABORTED' || axiosRetry.isNetworkOrIdempotentRequestError(err) ) {
      console.warn(`Timeout - RETRY ${++retryCount}`);
      return true;
    }
    return false;
  },
});

ax( {
  url: 'http://localhost',
  method: 'GET',
  timeout: 1000
}).then(resp => console.log(resp.data));
```

#### Expected behavior
It should get a timeout error twice and then receive and log an empty array.

#### Environment
 - Axios Version 1.1.0
 - Node.js Version 18.7
 - Additional Library Versions axios-retry 3.3.1, nock 13.2.9

**Comment by chrno1209** [comment]
I am having the same issue, had to do a work around by removing all invalid headers (using interceptor) before sending request.

**Comment by grenik** [comment]
Seems relevant to https://github.com/axios/axios/issues/5089 which shall be fixed in https://github.com/axios/axios/pull/5090

**Comment by KrayzeeKev** [comment]
@grenik Apparently, #5090 is done and merged. Or replaced with #5162. NOT FIXED. #5162 is merged and current v1.x branch has the same fault.

**Comment by KrayzeeKev** [comment]
@DigitalBrainJS  I'm sorry. I had removed an actual URL in favour of a fake one so the successful call at the end never happened. Added another .get to the nock call above. 
I also removed the .default from the axios require which was legal in the early 1.x releases still, I think but has become illegal now. There's a PR for the next release that puts it back. But it does nothing. 
Code above should now behave as advertised.

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
