### ISSUE TITLE
1.2.0-alpha.1

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios#5249]
Hi 👋 

We have released 1.2.0-alpha.1 please can you test this version and provide feedback to us. You can use this by running: 

```bash
npm i axios@1.2.0-alpha.1
```

Thanks

**Comment by krutoo** [comment]
Looks like #5154 has been fixed, thanks to all contributors

**Comment by Ashabu** [comment]
#5152 is fixed for me as well, thanks to all contributing

**Comment by OVO-Josh** [comment]
#5101 still occurs for me unfortunately (thanks to all who contributed though!)

**Comment by dhensby** [comment]
#5000 Doesn't appear to be fixed (at least not under my use-case: Using the settle helper in tests).

**Comment by jasonsaayman** [comment]
@OVO-Josh https://github.com/axios/axios/issues/5026#issuecomment-1311000557 seems there is not an apparent solution due to this Jest issue https://github.com/facebook/jest/issues/9771

**Comment by jasonsaayman** [comment]
Yeah, @dhensby #5000 will probably not happen any time soon. We cannot declare that as part of the public API. I do welcome anyone who needs that to explain or show me their use case, maybe then I can come up with a solution.

**Comment by dhensby** [comment]
@jasonsaayman I think I'll open a new issue specifically about the `settle` use-case. It's documented in the READMEs as a utility for testing purposes, so seems pretty essential to have the settle helper exported.

**Comment by irishtomwalsh** [comment]
this fixed issue #5208 for me

**Comment by arthurfiorette** [comment]
Can we get #4922 into v1.2? Its been there waiting for merge for a while now...

**Comment by TomiOhl** [comment]
I don't seem to encounter #5101 anymore with this version.

**Comment by jasonsaayman** [comment]
It seems that TS > JS transpiling is a problem with the latest release. Will see if I can debug that

**Comment by Giftia** [comment]
#5195 Sadly, still occurs.

**Comment by tada5hi** [comment]
@jasonsaayman would be great if you could create a `v1.2.0` release with current features & fixes.

**Comment by Max-DVS** [comment]
Thanks! it works again with react native, since 1.0.0 it would complain about restrict mode and had to downgrade to 0.27

**Comment by tada5hi** [comment]
https://github.com/axios/axios/issues/5089 is still an issue in `v1.2.0-alpha.1`

**Comment by aymendps** [comment]
Changed from 1.1.3 to this. Can confirm this version fixes the issue in typescript when importing axios leads to axios being undefined.

**Comment by jasonsaayman** [comment]
This version has now been released, thanks everyone for your help in getting it over the line 😄

**Comment by phloose** [comment]
> Yeah, @dhensby https://github.com/axios/axios/issues/5000 will probably not happen any time soon. We cannot declare that as part of the public API. I do welcome anyone who needs that to explain or show me their use case, maybe then I can come up with a solution.

We developed a fetch-based adapter for axios according to the [readme in the adapters module](https://github.com/axios/axios/blob/v1.1.3/lib/adapters/README.md). With the new strict export policy regarding lib-exports we cannot use helpers and core functions `settle`, `buildFullPath`, `buildUrl` as @dhensby has said here and in #5254 as well as others have said in #5000. If you can point us to an alternative to using settle or other helpers please let us know. Also if this will not be updated the readme for the adapters module should be updated
