### ISSUE TITLE
Breaking behavior in params serialization in 0.28.0

### ISSUE THREAD

**Issue by rchl** [axios/axios#6274]
### Describe the bug

In 0.28.0 there is a breaking change to params serialization that wasn't mentioned as such in the changelog.

Probably related to c05ad4895293ac8e0bbb90b28e0772571a97cdd5 and 807918bda2768df0f3a3422abd4e30d16694092d

If this is an expected change then it should have been noted in the changelog as breaking. Otherwise it should be fixed.

@DigitalBrainJS 

### To Reproduce

Send a get request with one of the `params` values being an object with key/value properties.

### Code snippet

```js
axios.get('foo', {
                params: {
                    p: {a: 'z'}
                },
            });
```

### Expected behavior

Previously the `p` param would be serialized as such: `&p={"a":"z"}`
With 0.28.0: `&p[a]=z`

### Axios Version

0.28.0

**Comment by odGit** [comment]
Might be a duplicate of #6262

**Comment by briwa** [comment]
I think we can close this since #6263 which is to solve #6262 is merged and released in v0.28.1. See: 3021e0ddbdeb5cd40e9e296851a8bd8ff45116d3

**Comment by rchl** [comment]
No, it's not fixed. Just tested with 0.28.1.

Feel free to test yourself by making a request like in the initial comment and checking brower network inspector for what is being sent.
I've tried it on an client side (in a browser environment).

**Comment by briwa** [comment]
@rchl I see, perhaps it is a different issue. v0.28.1 allows you to have a custom `paramsSerializer.serialize` options which you could use to achieve what you expected, otherwise I'd say this is just a standardization, i.e. stringified params vs params by key

**Comment by rchl** [comment]
Would make sense to keep the old behavior to prevent breaking changes unless there is a good reason to deviate. And if there is then it should be clearly marked as a breaking change and there should be good reason for it (standards compliance or similar).

**Comment by h82nk** [comment]
I can also confirm this is a breaking change in 0.28.0. Our axios get requests return a differently serialized request headers than in previous 0.27.2 version, resulting in 500 errors. Using a paramsSerializer.serialize options did not help in my case

**Comment by butchtm** [comment]
@briwa @rchl would anyone have an serializer options example that would restore the behavior to the version prior to 0.28?

**Comment by haydenk82** [comment]
@butchtm I've tried to replicate the serialization behavior that was implemented in prior versions to 0.28 below

/**
 * Creates a URL-encoded query string from a given set of parameters.
 * @param {Object} params The parameters to encode into a query string.
 * @returns {string} The URL-encoded query string.
 */
function createQueryString(params: any): string {
    return Object.keys(params).reduce((acc, key) => {
        const value = params[key];
        if (typeof value === 'object' && value !== null && !(value instanceof Date)) {
            return acc + `${acc.length ? '&' : ''}${encodeURIComponent(key)}=${encodeURIComponent(JSON.stringify(value))}`;
        } else {
            return acc + `${acc.length ? '&' : ''}${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
        }
    }, '');
}

**Comment by haydenk82** [comment]
@butchtm I've tried to replicate the serialization behavior that was implemented in prior versions to 0.28 below

```
/**
 * Creates a URL-encoded query string from a given set of parameters
 * @param {Object} params The parameters to encode into a query string
 * @returns {string} The URL-encoded query string
 */
function createQueryString(params: any): string {
    return Object.keys(params).reduce((x, key) => {
        const value = params[key];
        if (typeof value === 'object' && value !== null && !(value instanceof Date)) {
            return x + `${x.length ? '&' : ''}${encodeURIComponent(key)}=${encodeURIComponent(JSON.stringify(value))}`;
        } else {
            return x + `${x.length ? '&' : ''}${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
        }
    }, '');
}

```

**Comment by skreis** [comment]
I've similarly observed a breaking change that I believe is related and was not included in the CHANGELOG.

Specifically, before `0.28.0`, if I have a querystring like:

```
const qs = {
    foo: 1,
    bar: 'xyz',
    baz: { }
};
```

When passed to axios.get – like `axios.get("https://some.uri", { params: qs })` – the resulting query params that are passed to `https://some.uri` in the constructed request are:

```
foo=1&bar=xyz&baz=%7B%7D
```

In 0.28.0, that same request yields the following querystring params (_excluding the `baz` param entirely_):

```
foo=1&bar=xyz
```

---

This is a seemingly understandable optimization, but is in fact a breaking change for anyone who relies on that functionality to remain as-is.

**Comment by Zohar727** [comment]
it seems the problem has resolved in this [issuse](https://github.com/axios/axios/pull/6263/commits/300322395805bc5174ca86c81b7db275edda2756),but the lastest version v0.28.1 also has this problem

**Comment by Jeremias98** [comment]
Any update of this? Version v0.28.1 does not solve this issue, is there an ETA for this fix?

**Comment by bestis** [comment]
Have to say this is very badly handled and like makes really wonder should one even try to use the newer axios versions in the future is this is how the project is maintained. 

Minor release. Breaking change. No mention about it. Then releases a patch version that has ability to control it, but no mention on officially how to keep the backwards compatible behavior. And then 🦗 🦗 🦗

**Comment by jasonsaayman** [comment]
this was done in v0.x of the library if you follow the semversion rules, this is actually allowed and thats why we made the change. if we would like to revert this change please open a PR
