### ISSUE TITLE
Timeout doesn't work

### ISSUE THREAD

**Issue by rafalschmidt97** [axios/axios#647]
Hi,
I cant implement timeout request.

What i did:

`
axios.defaults.timeout = 100000;
`

My action:

```
export function login(data) {
  return dispatch => {
    return axios.post('auth/login', null,{
      headers: {
        username: data.email,
        password: data.password,
      },
     timeout: 5000
    })
    .then(res => {
      const token = res.data.token;
      localStorage.setItem('Token', token);
      setAuthToken(token);
      dispatch(setAccount(jwtDecode(token)));

      return res;
    });
  };
}
```

And react side:

```
this.props.login(this.state).then(
        (res) => {
          console.log('sign-in');
          console.log(res);
          browserHistory.push('/student/dashboard');
        },
        (err) => {
          console.log('sign-in error');
          console.log(err.response.data);
          alert(err.response.data.message);
          //isLoading: false
        }
      );
```

Where i made mistake?

Thanks for every answers!

**Comment by hoangtubatu** [comment]
Timeout doesn't work too on react native.
This is my code:
        axios.get('http://10.0.2.2:8080/api/login', {
            params: {
                name: 123,
                pass: 456,
            },
            'timeout': 1000,
        })
            .then((response) => {
             // code here
            })
            .catch((error) => {
             // code here
            });

**Comment by Lxxyx** [comment]
Same problem.

**Comment by robcaldecott** [comment]
Same issue here with Chrome (Windows). Chrome seems to ignore any timeout setting. I'm setting it when making a request like this:

```js
axios({
  url: 'myurl',
  method: 'post',
  data: data,
  timeout: 1000
})
```

**Comment by Sutikshan** [comment]
Yes, supplied timeout config is being ignored. I am creating axios instance as following :-
`    const instance = axios.create({
      baseURL: this.apiBase,
      timeout: 5000,
      responseType: 'json',
      headers: {...},
    });`

But my calls are failing as they are timing out on 3000 ms. 
`timeout of 3000ms exceeded { Error: timeout of 3000ms exceeded\n at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:15:15)\n at Timeout.handleRequestTimeout [as _onTimeout] (/usr/src/app/node_modules/axios/lib/adapters/http.js:201:16)\n `

**Comment by camflan** [comment]
Same, timeout doesn't work - I've implemented my own timeout functionality using CancelToken. I'd love to remove this cancelling boilerplate

**Comment by MrLyfing** [comment]
Still doesn't work on me either using React Native 0.42.3 .. 
@camflan Would you show how you implemented your own timeout functionality with CancelToken ? Thanks :)

**Comment by camflan** [comment]
Sure! My actual implementation is using redux-saga, which might be confusing if you're not used to using them. If you are, I'm happy to show that too. 

Here's a quickly written, slightly contrived, (and never executed 😄 ) example for you that should help.

```
import { axios, CancelToken } from "axios"

function updateUserInfo(data, cancel) {
    return axios
        .post(URL, data, {
            // CancelToken takes a func that has the cancel function for it's param
            // we'll set it to our cancel variable that we passed in. Then we'll
            // call this function where/when we need to cancel this request
            cancelToken: new CancelToken(c => (cancel = c)),
        })
        .then(r => r)   // return the response
        .catch(err => {
            throw err   // throw our error because the request failed
        })
}

function submitForm(formData) {
    let cancel = null // declare our cancel variable to hold the cancel func

    const results = updateUserInfo(formData, cancel)
        .then(resp => console.log(resp))
        .catch(err => {
            throw err
        })

    setTimeout(() => {
        if (!results.ok) {
            // if the timeout fires, and our results didn't come back
            // then we'll call the cancel func set by CancelToken
            cancel()
        }
    }, 5000)
}
```

**Comment by zhuyifan2013** [comment]
same issue!!

**Comment by zhuyifan2013** [comment]
I found the `timeout` in  axios is `response timeout` , not `connection timeout` , for example if you connect a local ip address 192.168.11.11 which dose not exist, it will take a long time , the timeout looks like invalid , but if you connect to a normal , well-connected server , the timeout take effects.
My platform is react-native.

So I solve this problem by the method provided by @camflan , thanks very much , my code : 

```javascript

const connectToServer = ip => {
    let source = CancelToken.source();
    setTimeout(() => {
        source.cancel();
    }, 300);
    return axios.get(ip + '/config', {cancelToken: source.token}).then((result) => {
        // My logic
    })
};

```

**Comment by frevib** [comment]
Solution of @camflan / @zhuyifan2013 works for me with React-Native 0.41.2 on Android. @zhuyifan2013's code calls always calls source.cancel(). Writing it like this would make it only cancel when there is no response:


```javascript
function loginButtonPressed(username, password) {
    return async (dispatch) => {
        const source = CancelToken.source();
        try {
            let response = null;
            setTimeout(() => {
                if (response === null) {
                    source.cancel();
                }
            }, 4000);
            dispatch(authenticationPending());

            response = await axios.post('auth/login',
                {username, password},
                {cancelToken: source.token});
            dispatch(authenticationSuccess());
        } catch (error) {
            dispatch(authenticationFailed());
        }
    };
}
```

**Comment by montogeek** [comment]
@rshmiraf Is the issue fixed for you?

**Comment by robomc** [comment]
Is there a reason to think this is fixed? There's no code change referenced in this or the linked Axios ticket.

**Comment by baijunjie** [comment]
same issue!

Sometimes `timeout` doesn't work, I have to use `CancelToken`.

**Comment by joelnet** [comment]
Still an issue in 2019. I have abandoned the `timeout` option since it is unreliable.

Now I must manually timeout axios using the `CancellationToken` method listed above.

**Comment by nelsonomuto** [comment]
I created a wrapper for this to make is simply throw a timeout error you can catch 
https://www.npmjs.com/package/@nelsonomuto/axios-request-timeout
```
import axiosRequest from '@nelsonomuto/axios-request-timeout';

try {
  await axiosRequest({
    url: 'https://www.cnn.com/',
    method: 'GET',
    timeout: 10
  });
} catch(error) {
  console.log({ error });
  expect(error).toEqual({'message': 'timeout cancel'});
}
```

**Comment by LeviYoder2112** [comment]
I've implemented @joelnet 's cancelToken solution to the timeout issue on Android devices , and it is mostly working fine, but with some weird caveats. 

The code: 

```const axios = require('axios').default;
    let source = axios.CancelToken.source();
    setTimeout(() => {
      source.cancel('timeout');
    }, 1);
    return axios
      .post(
        URL,
        inputData,
        {cancelToken: source.token},
      )
      .then(result => {
        console.log(result);
      })
      .catch(function(thrown) {
        if (axios.isCancel(thrown)) {
          console.log('Request canceled', thrown.message);
        } else {
          alert(thrown);
        }
      });
```

Context:
This function is being called upon by a 'submit'  button pressed by the user, and it's sending a small bit of data to Firebase. 

The weird behavior: 
I set the timeout to 1ms, so `source.cancel()` is called every time the function is called. 
Despite `source.cancel()` being triggered upon every function call , if the app has been started in the last minute or so, it will still successfully send the data to firebase upon the first and/or second button press. However, if I start the app up, and wait a minute or two before pressing the 'submit' button, `source.cancel()` is still called, but it works properly. 

The function is defined within a react-redux action creator, and called from a component that has accessed it via `mapDispatchToProps`.

Has anyone else noticed behavior like this??

**Comment by rafalschmidt97** [comment]
Wow. I've opened this issue almost three years ago and since then and people still encounter problems when it comes to timeout. I think the team of axios might forget about this one so next time instead of adding another comment consider opening a new one. You can always attach this one as a reference and for now, I'll close this. Good luck guys!

**Comment by benb1983** [comment]
This still isn't fixed in 0.19.2 btw...

**Comment by epatrasc** [comment]
> This still isn't fixed in 0.19.2 btw...

Hi, is your problem on nodejs platform?
If so what version?
I'm trying to reproduce this issue on my local machine (nodejs environment) and timeout always works.

From the previous comments on this issue it looks like related to browser or mobile environments.
@benb1983

**Comment by blombard** [comment]
@epatrasc You can reproduce it like that : 

```
const axios = require('axios');

axios({
    method: 'POST',
    url: 'http://example.com:81',
    params: {
      foo: 'bar'
    },
    timeout: 100
  })
  .then(data => console.log(data))
  .catch(error => console.log(error))
```

**Comment by arfa123** [comment]
I solved the problem by adding timeout into the axios configuration before data parameter. For some reason, timeout parameter will not work if placed after the data parameter.
```
axios({
      method: 'post',
      timeout: 1000,
      url: 'http://192.168.0.1:5000/download',
      data: {
          access: data.token
      }
})
.then(function (response) {
    alert(response.data);
})
.catch(function (error) {
    alert("There was an error in communicating to server");
});
```

**Comment by epatrasc** [comment]
> @epatrasc You can reproduce it like that :
> 
> ```
> const axios = require('axios');
> 
> axios({
>     method: 'POST',
>     url: 'http://example.com:81',
>     data: {
>       foo: 'bar'
>     },
>     timeout: 100
>   })
>   .then(data => console.log(data))
>   .catch(error => console.log(error))
> ```

Hey thanks for the reply and the example. 
So the problem is related to the `POST` request and is independent from the platform.

**Comment by epatrasc** [comment]
> I solved the problem by adding timeout into the axios configuration before data parameter. For some reason, timeout parameter will not work if placed after the data parameter.
> 
> ```
> axios({
>       method: 'post',
>       timeout: 1000,
>       url: 'http://192.168.0.1:5000/download',
>       data: {
>           access: data.token
>       }
> })
> .then(function (response) {
>     alert(response.data);
> })
> .catch(function (error) {
>     alert("There was an error in communicating to server");
> });
> ```

I have tried with both timeout before and after but same result, it times out but after ~1min.
--> `node test.js  0.13s user 0.05s system 0% cpu 1:15.47 total`

I used @arfa123's example code for testing.

this is the result:
```
time node test.js
running
end of the code not of the execution
{ Error: connect ETIMEDOUT 93.184.216.34:81
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '93.184.216.34',
  port: 81,
  config:
   { url: 'http://example.com:81',
     method: 'post',
     data: '{"foo":"bar"}',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.19.2',
        'Content-Length': 13 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 100,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  request:
   Writable {... },
     writable: true,
     _events:
      [Object: null prototype] {
        response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '/',
        method: 'POST',
        headers: [Object],
        agent: undefined,
        agents: [Object],
        auth: undefined,
        hostname: 'example.com',
        port: '81',
        nativeProtocols: [Object],
        pathname: '/' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 13,
     _requestBodyBuffers: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST / HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.19.2\r\nContent-Length: 13\r\nHost: example.com:81\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: [Function: emitRequestTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://example.com:81/' },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function] }
node test.js  0.13s user 0.05s system 0% cpu 1:15.47 total
```

**Comment by jlgouwyapizr** [comment]
It seems the problem is not fixed yet. 
I just encountered on my AWS lambda. 

I will try with CancelToken soluce ! Thx

**Comment by crizzs** [comment]
I am still facing this issue in our node app
