### ISSUE TITLE
Request to HTTPS with HTTP proxy fails

### ISSUE THREAD

**Issue by kparkov** [axios/axios#925]
### Summary

Trying to do a HTTPS request with a HTTP proxy fails.

```javascript
const req = await axios({
  url: 'https://somedomain.com',
  proxy: {
    host: '89.151.146.7',
    port: 6060,
    auth: {
      username: 'myname',
      password: 'mypass',
    },
  },
});
```

Results in:

```
Error: write EPROTO 140736379442112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794
```

The problem is already described by @chovy in this ticket, which ended up closed as OP did not have the same problem: https://github.com/mzabriskie/axios/issues/662

@chovy says:

> I still have this issue not being able to hit an https url with an http proxy. I can do it fine in request and also in curl from shell. Something not working with axios. I get an EPROTO error.

### Context

- axios version: v0.16.1
- Environment: node v7.10.0, Mac OSX Sierra

**Comment by gigachel** [comment]
I'm having the same problem of https request over proxy. I do not want to move to request.js. 

 ```
return axios({
   url: 'https://site.com',
   proxy: {
        host: 'proxy.xxxxxx.com',
        port: 3128
    }
})
```
Result:
`Error: write EPROTO 139800246822688:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794`

request.js and curl in this situation works well.

### Context

- axios version: v0.16.1
- Environment: node v6.9.5, CentOS release 6.8 (Final)

**Comment by Khaledgarbaya** [comment]
Me and a colleague of mine identified the problem, a PR should be coming soon

**Comment by Khaledgarbaya** [comment]
the PR is here https://github.com/mzabriskie/axios/pull/959

**Comment by mpcen** [comment]
Same issue here: Requesting https resources behind an http proxy.

`axios.get('https://resources.json', {
   proxy: {
      host: 'http://my.proxy.com',
      port: 12345
   }
})
   .then(() => {})
   .catch(() => {});`

Result:
`Error: getaddrinfo ENOTFOUND http://my.proxy.com http://my.proxy.com:12345`

**Comment by kunokdev** [comment]
Any progress on this so far?

**Comment by Meg4mi** [comment]
Same problem here.

Any news ?

**Comment by kunokdev** [comment]
My problem was that I had to send GET request to `https` domain which wasn't certified. In curl solution was to use `-k` or `--insecure` flag. I couldn't find Axios solution tho, but with `request` lib I done it like so; might give you idea:

```
const agentOptions = {
    host: '10.100.0.10',
    port: '443',
    path: '/',
    rejectUnauthorized: false,
  }

const agent = new https.Agent(agentOptions)
request({
      url: 'https://10.100.0.10/devices/status?authUser=syscdr&authPass=PenfnVch8QfeDy4J',
      method: 'GET',
      agent,
    }, (err, resp, body) => {
...
```

**Comment by mistermoe** [comment]
Feel free to use [this](https://www.npmjs.com/package/axios-proxy-fix) until they get #959 merged.

**Comment by PedramMarandi** [comment]
Same here, btw @mistermoe's PR works fine

**Comment by Sneko** [comment]
@mistermoe I just left work without making it succeeded :(

I use this package : https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-messenger

And if I replace "axios" by yours, the following error disappears:
"Error: write EPROTO 139800246822688:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794"

But I have something like:
"Error: getaddrinfo EAI_AGAIN"

I notice that the Messenger plugin makes requests like that:
`let client = axios.create({ ... });
client.get('...')`

Did you succeed by this way?

Thanks!

**Comment by cur3n4** [comment]
Any chance of merging this? Could we leverage the newly added config.transport to avoid this issue?

**Comment by rightaway** [comment]
Looking to use this as well, can it be merged?

**Comment by skuarch** [comment]
ups, same problem here!

**Comment by Sitronik** [comment]
Unfortunately, this pull request doesn't merged, but I fixed this issue too https://github.com/Sitronik/axios

**Comment by jan-molak** [comment]
Had a similar issue recently, my solution was to use an HTTPs-over-HTTP tunnel and specify port 443 explicitly in the URL:

```typescript
import axios, { AxiosInstance } from 'axios';
import * as tunnel from 'tunnel';

['http_proxy', 'https_proxy', 'no_proxy'].
    forEach(variable => delete process.env[variable]);

const tunnel = tunnel.httpsOverHttp({
    proxy: {
        host: 'proxy.mycorp.com',
        port: 8000,
    },
});

const httpClient: AxiosInstance = axios.create({
    baseURL: 'https://some.api.com:443',
    httpsAgent: tunnel,
});
```

More about the solution in [this article](https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d).

Hope this helps,
Jan

**Comment by Sitronik** [comment]
@jan-molak My fix is easy to use:
1. npm install axios-https-proxy-fix
2. Then
```javascript 
import axios from 'axios-https-proxy-fix'; 

const proxy = {
  host: 'some_ip',
  port: some_port_number,
  auth: {
    username: 'some_login',
    password: 'some_pass'
  }
};

const result = await axios.get('some_https_link', {proxy});
```

**Comment by b4hand** [comment]
@jan-molak's solution worked for me as well. It would really be nice to not have to force the port number on the url though.

**Comment by Alexis374** [comment]
@jan-molak  @Sitronik   I tried your solution but get Error: socket hang up.
What I want is see how the request go through charles,so I open charles,and set proxy to {host:'127.0.0.1',port:8888}. I don't know whether it is suitable to use your solution

**Comment by astappev** [comment]
Any change to be included in 0.19.0?

**Comment by emilyemorehouse** [comment]
@astappev this definitely looks like it needs a fix ASAP. There's a lot of related issues and PRs that I need to sift through, but I'll add it to my 0.19.0 roadmap.

**Comment by astappev** [comment]
@emilyemorehouse, do you have any estimation when it will be released?
The PR #959 solve critical part of the issue, other issues like proxying redirections and so can be improved later.

**Comment by anhnt** [comment]
@Sitronik tha works for me thanks

**Comment by necevil** [comment]
@jan-molak 's fix saved my day.
+1 to merging the PR.

**Comment by SrWildman** [comment]
Another +1 to merging this!!

**Comment by raphaelsoul** [comment]
Same issue here

**Comment by necevil** [comment]
+1 Still using work arounds mentioned above but would love to see this work out of the box.

**Comment by fractalzombie** [comment]
+1 When you fix this?

**Comment by Makoehle** [comment]
@Sitronik please add PR. Your package works just fine. `axios.defaults.proxy = {host: ip, port: port}`

**Comment by m2jobe** [comment]
Still an issue, would use that package but its many commits behind? Would that be a non issue :S

**Comment by Makoehle** [comment]
> would use that package but its many commits behind?
Same for me while waiting for that change I'm going for node-fetch + httpsProxyAgent. Works fine.

**Comment by m2jobe** [comment]
@Makoehle  

Hey I ended up getting it to work, try export http and https to "" on your terminal


`
export http_proxy=""
export https_proxy=""
`

**Comment by lderzhavets** [comment]
Waiting for merge too. Why it is so long?

**Comment by emilyemorehouse** [comment]
#959 was merged and is available in 0.19.0-beta.1

**Comment by czl032405** [comment]
I can not solve it out in 0.19.0-beta.1, but  I fixed like this 
```
// default axios usage
import * as ProxyAgent from "proxy-agent";
const proxyAgent = new ProxyAgent(process.env.HTTPS_PROXY);  // http://127.0.0.1:1080
Axios.defaults.httpsAgent = proxyAgent;
Axios.defaults.proxy = false;

// google api usage
const Sheets = google.sheets({
    version: "v4",
    auth: key,
    httpsAgent: /dev/.test(process.env.NODE_ENV) ? proxyAgent : false,
    proxy: false
});
```

**Comment by Khaledgarbaya** [comment]
0.19.0-beta.1 should fix the issue, I am closing the issue and feel free to create a new one if anyone still having the issue

**Comment by necevil** [comment]
@Khaledgarbaya I am still having this issue with 0.19.0-beta.1
My question is what should my proxy request look like (and how does the isHttps flag work?).

I assumed that for HTTPS over HTTP I would simple set the http url / port for the proxy like this:

```
axiosRequestOptions.proxy = {
            host: '192.0.01',
            port: '8888',
            // isHttps: true, ?
        }
```

That being said the above still fails so I am wondering if it is a configuration / documentation issue where my structuring of the proxy property / object is the cause.

**Comment by Sitronik** [comment]
@necevil 
host: '192.0.01'

**Comment by bidhan-a** [comment]
The 0.19.0-beta.1 still **does not** work. Wasted a lot of time on this. Switched to the [requests](https://github.com/request/request-promise) library and it worked like a charm on the first try.

**Comment by mrodrig** [comment]
After updating to `0.18.0` this seems to be working for me. I had to specify the following options for my use case though:

```javascript
axios.get('<some_url_on_corporate_intranet>', {
        proxy: false,
        httpsAgent: https.Agent({
            rejectUnauthorized: false // Allows the use of self-signed certificates (not recommended)
    })
```

**Comment by redbearder** [comment]
tried all solution and all failed base on axios 0.18
final solution :
install nginx module [ngx_http_proxy_connect_module](https://github.com/chobits/ngx_http_proxy_connect_module)
then request https url via http proxy with [request-promise](https://github.com/request/request-promise)

**Comment by chovy** [comment]
You don’t need Nginx if you’re using request. Request handled proxies fine. 

-
Anthony

**Comment by YassienW** [comment]
2 years later, still broken!!!

**Comment by chovy** [comment]
Use request promise. 

Anthony
http://profullstack.com

**Comment by YassienW** [comment]
Here's what i did for those who stumble upon this and still want to use axios:

```javascript
const HttpsProxyAgent = require("https-proxy-agent"),
      axios = require("axios");

const agent = new HttpsProxyAgent({host: "proxyhost", port: "proxyport", auth: "username:password"})

//use axios as you normally would, but specify httpsAgent in the config
axios = axios.create({
    httpsAgent: agent
});
```
This will let you make https requests over an http proxy, simple and neat.

**Comment by klibs** [comment]
Just ran into this issue myself. Hoping you guys can fix this at some point.

**Comment by YassienW** [comment]
Should probably open a fresh issue

**Comment by YassienW** [comment]
According to the 0.19.0 release, this has been fixed. Since it obviously hasn't, a new issue should be opened

**Comment by axiac** [comment]
This functionality is still broken in axios 0.19.
Version 0.19.0 fails with the message _"Error: Protocol "http:" not supported. Expected "https:""_
Version 0.19.1 fails with _"Error: timeout of 1000ms exceeded"_. Increasing the timeout doesn't help. The proxy server expects a `CONNECT` request while axios sends a `GET` request.
